services:
  universaldevice:
    environment:
      - TZ=Europe/Moscow
    build: .
    image: universaldevice:1.13.3
    network_mode: bridge
    expose:
      - "7315"
      - "7316"
    ports:
      - "0.0.0.0:7315:7315"
      - "0.0.0.0:7316:7316"
    restart: always
    volumes:
      - ./opt:/opt/UniversalDevice

